### PR TITLE
Backward compatible python3 fixes

### PR DESCRIPTION
**Pull request by tammojan**
This PR makes CMN_Binviewer at least start on python3. All changes should be backward compatible with python2. I did see the py3 branch, but that had backward incompatible changes.

Sorry for making the diff larger than necessary by removing trailing whitespace, that's a feature of my editor. Press 'ignore whitespace' in the diff to see only relevant changes.

### CODE REVIEW

**Comment by dvida** [comment]
Hi Tammo - thanks, but see the py3 branch, all py3 compatability changes have already been implemented there. I just need to find time to test them and merge them into the main branch.

**Comment by tammojan** [comment]
If you merge the py3 branch the program will be incompatible with python 2. That is fine with me (python2 has been unsupported for about a year now), but will lead to some transition difficulties

**Comment by tammojan** [comment]
I compared my branch with the py3 branch, and it contains the same fixes, but with backward compatibility. I previously overlooked one thing with the truth-gen iterator but now added a fix for that to this PR.

One possible issue is that the py3 branch has a different setting for `orientation` in config.ini, so that's something to have a look at when merging that branch.

Maybe I'm naive, but I think merging into the main branch should be a matter of pressing the green button :)

**Comment by tammojan** [comment]
Note that c0ee068 and ccf1453 were not part of the py3 branch, so on that branch confirmation does not work in python3.

**Comment by tammojan** [comment]
I think all of these changes were also taken in #8.

**Pull request closed without merging**
